version: '3.4'

services:
  webapi:
    build:
      context: ./Products
      dockerfile: Dockerfile
    ports:
      - "8000:80" 
      - "44300:443" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Products;User Id=SA;Password=NewStrongP@ssw0rd;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "NewStrongP@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
