run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - name: Restore dependencies
        run: dotnet restore Products.sln
      - name: Build
        run: dotnet build Products.sln --no-restore
      - name: Test
        run: dotnet test Products.sln --no-build
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Automated commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.VM_PAT }}
          branch: ${{ github.ref }}
